# Makefile for generating React client

# Targets
.PHONY: generate-client

generate-client:
	npm run generate-client

start:
	npm start

# npm install -g npm-check-updates
update-deps:
	ncu --upgrade
	npm install
