# Makefile for generating React client

# Targets
.PHONY: generate-client test

generate-client:
	npm run generate-client

start:
	npm start

test:
	npm test

# npm install -g npm-check-updates
update-deps:
	ncu --upgrade
	npm install
