[package]
name = "bidding_app"
version = "0.1.0"
authors = ["Tom Moulard <tom@moulard.org>"]
edition = "2021" # Changed to use the stable edition

[dependencies]
actix-web = "4.0.0"

[[bin]]
name = "bidding_app"
path = "src/main.rs"

[package.metadata]
rustfmt = { version = "1.8.0", default = true }
