/* tslint:disable */
/* eslint-disable */
/**
 * bidding_app
 * A simple bidding app
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: tom@moulard.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PurchaseRequest
 */
export interface PurchaseRequest {
    /**
     * 
     * @type {number}
     * @memberof PurchaseRequest
     */
    points: number;
}

/**
 * Check if a given object implements the PurchaseRequest interface.
 */
export function instanceOfPurchaseRequest(value: object): value is PurchaseRequest {
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function PurchaseRequestFromJSON(json: any): PurchaseRequest {
    return PurchaseRequestFromJSONTyped(json, false);
}

export function PurchaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'points': json['points'],
    };
}

export function PurchaseRequestToJSON(json: any): PurchaseRequest {
    return PurchaseRequestToJSONTyped(json, false);
}

export function PurchaseRequestToJSONTyped(value?: PurchaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points': value['points'],
    };
}

