services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bidding_app
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - type: bind
        source: /Users/tom.moulard/go/src/github.com/tommoulard/Yes/backend/src/sql/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
        bind:
          create_host_path: false

volumes:
  postgres_data:
