DROP SCHEMA IF EXISTS biding CASCADE;
CREATE SCHEMA biding;

CREATE TABLE biding.users (
	id  BIGSERIAL PRIMARY KEY,
	email       VARCHAR(200) NOT NULL UNIQUE,
	password    VARCHAR(200) NOT NULL,
	username    VARCHAR(50) UNIQUE NOT NULL,
	UNIQUE (username)
);
