name: Rust

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      run: rustup toolchain install stable

    - name: Cache cargo build
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Format
      run: cargo fmt -- --check

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Lint with rustfmt
      run: cargo fmt -- --check

    - name: Generate OpenAPI documentation
      run: cargo run --bin bidding_app > openapi_generated.json

    - name: Compare OpenAPI documentation
      run: diff -q openapi_generated.json openapi.json || (echo "OpenAPI documentation is not up to date" && exit 1)
