name: Rust

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      run: rustup toolchain install stable

    - name: Cache cargo build
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: backend

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Format
      run: cargo fmt -- --check
