name: Rust

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      run: rustup show

    - name: Cache cargo registry
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        path: ~/.cargo/registry

    - name: Cache cargo index
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        path: ~/.cargo/index

    - name: Cache cargo build
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        path: target

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Format
      run: cargo fmt -- --check

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Lint with rustfmt
      run: cargo fmt -- --check
